RegisterServerEvent('Tackle:Server:TacklePlayer')
AddEventHandler('Tackle:Server:TacklePlayer', function(src, targ)
	TriggerClientEvent("Tackle:Client:TacklePlayer", targ, src)
	print(GetPlayerName(src).." has tackled "..GetPlayerName(targ))
end)
